export type { DeleteTasksIdMutationKey } from './tasksHooks/useDeleteTasksId.ts'
export type { GetTasksQueryKey } from './tasksHooks/useGetTasks.ts'
export type { GetTasksInfiniteQueryKey } from './tasksHooks/useGetTasksInfinite.ts'
export type { GetTasksSuspenseQueryKey } from './tasksHooks/useGetTasksSuspense.ts'
export type { PostTasksMutationKey } from './tasksHooks/usePostTasks.ts'
export { deleteTasksIdMutationKey, deleteTasksId, useDeleteTasksId } from './tasksHooks/useDeleteTasksId.ts'
export { getTasksQueryKey, getTasks, getTasksQueryOptions, useGetTasks } from './tasksHooks/useGetTasks.ts'
export { getTasksInfiniteQueryKey, getTasksInfinite, getTasksInfiniteQueryOptions, useGetTasksInfinite } from './tasksHooks/useGetTasksInfinite.ts'
export { getTasksSuspenseQueryKey, getTasksSuspense, getTasksSuspenseQueryOptions, useGetTasksSuspense } from './tasksHooks/useGetTasksSuspense.ts'
export { postTasksMutationKey, postTasks, usePostTasks } from './tasksHooks/usePostTasks.ts'