/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteTasksIdMutationResponse, DeleteTasksIdPathParams, DeleteTasksId404 } from '../../../api/src/gen/types/DeleteTasksId.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteTasksIdMutationKey = () => [{ url: '/tasks/{id}' }] as const

export type DeleteTasksIdMutationKey = ReturnType<typeof deleteTasksIdMutationKey>

/**
 * @description Remove uma tarefa
 * {@link /tasks/:id}
 */
export async function deleteTasksId(id: DeleteTasksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteTasksIdMutationResponse, ResponseErrorConfig<DeleteTasksId404>, unknown>({
    method: 'DELETE',
    url: `/tasks/${id}`,
    baseURL: 'http://localhost:3001',
    ...requestConfig,
  })
  return res
}

/**
 * @description Remove uma tarefa
 * {@link /tasks/:id}
 */
export function useDeleteTasksId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteTasksIdMutationResponse>,
      ResponseErrorConfig<DeleteTasksId404>,
      { id: DeleteTasksIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteTasksIdMutationKey()

  return useMutation<ResponseConfig<DeleteTasksIdMutationResponse>, ResponseErrorConfig<DeleteTasksId404>, { id: DeleteTasksIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteTasksId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}