/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetTasksQueryResponse, GetTasksQueryParams } from '../../../api/src/gen/types/GetTasks.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getTasksQueryKey = (params?: GetTasksQueryParams) => [{ url: '/tasks' }, ...(params ? [params] : [])] as const

export type GetTasksQueryKey = ReturnType<typeof getTasksQueryKey>

/**
 * @description Lista todas as tarefas ou filtra por título
 * {@link /tasks}
 */
export async function getTasks(params?: GetTasksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetTasksQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/tasks`,
    baseURL: 'http://localhost:3001',
    params,
    ...requestConfig,
  })
  return res
}

export function getTasksQueryOptions(params?: GetTasksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getTasksQueryKey(params)
  return queryOptions<ResponseConfig<GetTasksQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetTasksQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getTasks(params, config)
    },
  })
}

/**
 * @description Lista todas as tarefas ou filtra por título
 * {@link /tasks}
 */
export function useGetTasks<
  TData = ResponseConfig<GetTasksQueryResponse>,
  TQueryData = ResponseConfig<GetTasksQueryResponse>,
  TQueryKey extends QueryKey = GetTasksQueryKey,
>(
  params?: GetTasksQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetTasksQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getTasksQueryKey(params)

  const query = useQuery(
    {
      ...(getTasksQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}