/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetTasksQueryResponse, GetTasksQueryParams } from '../../../api/src/gen/types/GetTasks.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getTasksInfiniteQueryKey = (params?: GetTasksQueryParams) => [{ url: '/tasks' }, ...(params ? [params] : [])] as const

export type GetTasksInfiniteQueryKey = ReturnType<typeof getTasksInfiniteQueryKey>

/**
 * @description Lista todas as tarefas ou filtra por título
 * {@link /tasks}
 */
export async function getTasksInfinite(params?: GetTasksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetTasksQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/tasks`, params, ...requestConfig })
  return res
}

export function getTasksInfiniteQueryOptions(params?: GetTasksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getTasksInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetTasksQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetTasksQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetTasksQueryParams['next_page']
      }
      return getTasksInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @description Lista todas as tarefas ou filtra por título
 * {@link /tasks}
 */
export function useGetTasksInfinite<
  TData = InfiniteData<ResponseConfig<GetTasksQueryResponse>>,
  TQueryData = ResponseConfig<GetTasksQueryResponse>,
  TQueryKey extends QueryKey = GetTasksInfiniteQueryKey,
>(
  params?: GetTasksQueryParams,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetTasksQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getTasksInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getTasksInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}