/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostTasksMutationRequest, PostTasksMutationResponse } from '../../../api/src/gen/types/PostTasks.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postTasksMutationKey = () => [{ url: '/tasks' }] as const

export type PostTasksMutationKey = ReturnType<typeof postTasksMutationKey>

/**
 * @description Cria uma nova tarefa
 * {@link /tasks}
 */
export async function postTasks(data: PostTasksMutationRequest, config: Partial<RequestConfig<PostTasksMutationRequest>> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostTasksMutationResponse, ResponseErrorConfig<Error>, PostTasksMutationRequest>({
    method: 'POST',
    url: `/tasks`,
    baseURL: 'http://localhost:3001',
    data,
    ...requestConfig,
  })
  return res
}

/**
 * @description Cria uma nova tarefa
 * {@link /tasks}
 */
export function usePostTasks<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<PostTasksMutationResponse>, ResponseErrorConfig<Error>, { data: PostTasksMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<PostTasksMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postTasksMutationKey()

  return useMutation<ResponseConfig<PostTasksMutationResponse>, ResponseErrorConfig<Error>, { data: PostTasksMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postTasks(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}